### ISSUE TITLE
App crashes due to network issue

### ISSUE THREAD

**Issue by chihuazhang** [Sparker0i/Weather#60]
Studies have shown that mobile apps are prone to crashes due to a network issue, mainly because successful network calls return unexpected or no data. And we found that when this app(version 5.3.2)'s network returned data is null or some fields are null (JSON format), the app has crashed three times. the specific crash information is as follows:

> java.lang.NullPointerException: Attempt to invoke virtual method 'com.a5corp.weather.model.WeatherInfo$Main com.a5corp.weather.model.WeatherInfo.getMain()' on a null object reference
	at com.a5corp.weather.service.NotificationService.a(dalvik_source_coma5corpweather_656.apk)
	at com.a5corp.weather.service.NotificationService.a(dalvik_source_coma5corpweather_656.apk)
	at android.support.v4.a.w$a.a(dalvik_source_coma5corpweather_656.apk)
	at android.support.v4.a.w$a.doInBackground(dalvik_source_coma5corpweather_656.apk)
	at android.os.AsyncTask$2.call(AsyncTask.java:295)
	at java.util.concurrent.FutureTask.run(FutureTask.java:237)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
	at java.lang.Thread.run(Thread.java:818)

> java.lang.NullPointerException: Attempt to invoke virtual method 'int com.a5corp.weather.model.WeatherFort.getCod()' on a null object reference
	at com.a5corp.weather.b.b.a(dalvik_source_coma5corpweather_656.apk)
	at com.a5corp.weather.b.b.doInBackground(dalvik_source_coma5corpweather_656.apk)
	at android.os.AsyncTask$2.call(AsyncTask.java:295)
	at java.util.concurrent.FutureTask.run(FutureTask.java:237)
	at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:234)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
	at java.lang.Thread.run(Thread.java:818)

> java.lang.NullPointerException: Attempt to read from field 'com.a5corp.weather.model.WeatherFort com.a5corp.weather.model.Info.fort' on a null object reference
	at com.a5corp.weather.fragment.WeatherFragment.c(dalvik_source_coma5corpweather_656.apk)
	at com.a5corp.weather.activity.WeatherActivity$5.a(dalvik_source_coma5corpweather_656.apk)
	at com.mikepenz.materialdrawer.d$5.a(dalvik_source_coma5corpweather_656.apk)
	at com.mikepenz.materialdrawer.d$5.a(dalvik_source_coma5corpweather_656.apk)
	at com.mikepenz.a.b$1.onClick(dalvik_source_coma5corpweather_656.apk)
	at android.view.View.performClick(View.java:5198)
	at android.view.View$PerformClick.run(View.java:21147)
	at android.os.Handler.handleCallback(Handler.java:739)
	at android.os.Handler.dispatchMessage(Handler.java:95)
	at android.os.Looper.loop(Looper.java:148)
	at android.app.ActivityThread.main(ActivityThread.java:5417)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)

**Comment by Sparker0i** [comment]
Hi there, thanks for posting this. Sadly, I'm no longer supporting this edition of Simple Weather. Further development for Simple Weather will now be happening here: https://github.com/Sparker0i/Weather-Kotlin
